server:
  port: 8080
spring:
  application:
    #应用名称，可选
    name: xyl_delivery
  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: 123456
#  mysql主从复制配置
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源   主库
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.162.138:3306/reggie?characterEncoding=utf-8
        username: root
        password: 123456
      # 从数据源  从库
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.162.137:3306/reggie?characterEncoding=utf-8
        username: root
        password: 123456
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin  #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false

    #        配置bean定义允许覆盖置顶
  main:
    allow-bean-definition-overriding: true


      # 邮箱配置
  mail:
    host: smtp.exmail.qq.com  # 发送邮件的服务器地址
    username: 2902352334@qq.com # 登录163邮箱的账号
    password: zveenywgwxczdfgg  # 开启 IMAP/SMTP服务 获得的授权码,而不是163邮箱的登录密码
    default-encoding: UTF-8

#redis配置
  redis:
    host: localhost # 本地IP 或是 虚拟机IP
    port: 6379
#    password: root
    database: 0  # 默认使用 0号db
    cache:
      redis:
        time-to-live: 1800000  # 设置缓存数据的过期时间，30分钟

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

#文件上传路径
reggie:
  path: D:\img\


